version: "3.3"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu 
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "DummyPassword123#"
      ACCEPT_EULA: "Y"